[features]
seeds = false
skip-lint = false
[programs.localnet]
serum_gov = "6titGTyVcdPo8GfHhJi3fhgLGkSHuhaEPiDpiUqK45v4"
[programs.devnet]
serum_gov = "6titGTyVcdPo8GfHhJi3fhgLGkSHuhaEPiDpiUqK45v4"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "/Users/sayantank/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
