[features]
seeds = false
skip-lint = false
[programs.localnet]
serum_gov = "FLjKvZ1sANZud13kx6p6bKtaRKQtCC2VQaFN2aUysZUb"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "/Users/sayantank/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
