anchor_version = "0.25.0"

[features]
seeds = false
skip-lint = false

[programs.localnet]
serum_gov = "FBcTbv5rLy7MQkkAU2uDzAEjjZDeu2BVLVRJGxyz6hnV"

[programs.devnet]
serum_gov = "EDV6BNBY6pLb4aCJCc5LnELdA9xTywnDZ2m3cWfCbpwZ"

[programs.mainnet]
serum_gov = "FBcTbv5rLy7MQkkAU2uDzAEjjZDeu2BVLVRJGxyz6hnV"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "mainnet"
wallet = "/Users/sayantank/.config/solana/id.json"

[test.validator]
url = "https://api.mainnet-beta.solana.com"

[[test.validator.clone]]
address = "metaqbxxUerdq28cj1RbAWkYQm3ybzjb6a8bt518x1s" 

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
